/**
 * World Cup 2026 — top scorer candidates.
 * Exact order and names as specified.
 * `team` values MUST match the Hebrew names in flags.js for flag lookup.
 */
export const TOP_SCORERS = [
  { player: 'קיליאן אמבפה',           team: 'צרפת'            },
  { player: 'הארי קיין',               team: 'אנגליה'          },
  { player: 'מיקל אויארסבאל',          team: 'ספרד'            },
  { player: 'ארלינג הולאנד',           team: 'נורווגיה'        },
  { player: 'ליאו מסי',                team: 'ארגנטינה'        },
  { player: 'לאמין ימאל',              team: 'ספרד'            },
  { player: 'כריסטיאנו רונאלדו',       team: 'פורטוגל'         },
  { player: 'חוליאן אלברס',            team: 'ארגנטינה'        },
  { player: 'ראפיניה',                  team: 'ברזיל'           },
  { player: 'לאוטרו מרטינס',           team: 'ארגנטינה'        },
  { player: 'ויניסיוס ג\'וניור',        team: 'ברזיל'           },
  { player: 'אוסמן דמבלה',             team: 'צרפת'            },
  { player: 'מייקל אוליסה',             team: 'צרפת'            },
  { player: 'איגור טיאגו',             team: 'ברזיל'           },
  { player: 'קאי האברץ',               team: 'גרמניה'          },
  { player: 'רומלו לוקאקו',            team: 'בלגיה'           },
  { player: 'קודי חאקפו',              team: 'הולנד'           },
  { player: 'פלוריאן וירץ',            team: 'גרמניה'          },
  { player: 'פראן טורס',               team: 'ספרד'            },
  { player: 'ניק וולטמאדה',            team: 'גרמניה'          },
  { player: 'לואיס חאבייר סוארס',      team: 'קולומביה'        },
  { player: 'שארל דה קטלארה',          team: 'בלגיה'           },
  { player: 'לואיס דיאס',              team: 'קולומביה'        },
  { player: 'מתאוס קוניה',             team: 'ברזיל'           },
  { player: 'ג\'מאל מוסיאלה',           team: 'גרמניה'          },
  { player: 'אולי ווטקינס',            team: 'אנגליה'          },
  { player: 'ג\'וד בלינגהאם',           team: 'אנגליה'          },
  { player: 'פיל פודן',                team: 'אנגליה'          },
  { player: 'בוקאיו סאקה',             team: 'אנגליה'          },
  { player: 'דרווין נונייס',           team: 'אורוגוואי'       },
  { player: 'מרקוס תוראם',             team: 'צרפת'            },
  { player: 'רודריגו',                  team: 'ברזיל'           },
  { player: 'אלכסנדר איסאק',           team: 'שוודיה'          },
  { player: 'ויקטור גיוקרש',           team: 'שוודיה'          },
  { player: 'ניקו ויליאמס',            team: 'ספרד'            },
  { player: 'דושאן ולאחוביץ\'',         team: 'סרביה'           },
  { player: 'צ\'אבי סימונס',            team: 'הולנד'           },
  { player: 'כריסטיאן פוליסיק',        team: 'ארצות הברית'     },
  { player: 'ג\'ונתן דייויד',           team: 'קנדה'            },
  { player: 'אנטואן גריזמן',           team: 'צרפת'            },
  { player: 'אנדריק',                   team: 'ברזיל'           },
  { player: 'מוחמד סלאח',              team: 'מצרים'           },
  { player: 'ויקטור אוסימן',           team: 'ניגריה'          },
  { player: 'בנימין ששקו',             team: 'סלובניה'         },
  { player: 'סון יונג-מין',            team: 'קוריאה הדרומית'  },
  { player: 'ממפיס דפאי',              team: 'הולנד'           },
  { player: 'קווין דה בריינה',         team: 'בלגיה'           },
  { player: 'חאמס רודריגס',            team: 'קולומביה'        },
  { player: 'איוב אל-כעבי',            team: 'מרוקו'           },
  { player: 'ראול חימנס',              team: 'מקסיקו'          },
]
